### PR TITLE
Update react-redux to fix security issue

### PR DESCRIPTION
**Pull request by jbalboni**
There's a new lodash security advisory: https://www.npmjs.com/advisories/782. The lodash version used directly here is unaffected, but react-redux uses an older version. This updates react-redux to v5, which has no breaking changes and removes the lodash dependency. There's a v6, but it has more changes and I wanted to get this out quickly.

## Types of changes

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've reviewed the [guidelines for contributing to this repository](../CONTRIBUTING.md#how-to-contribute-to-us-forms-system).
- [x] I've checked style and lint with `npm run lint`.
- [ ] I built the production version with `npm run build`.
- [ ] I added tests to verify a bug fix or new functionality.
- [x] All tests pass locally with `npm test`.
- [ ] My change requires a change to the documentation, and I've updated the documentation accordingly.

### CODE REVIEW

**Comment by dmethvin-gov** [comment]
@jbalboni when I build this locally I also see changes in `styles.css` and `styles.css.map`. They're pretty extensive. However, I also see them in the head of `1.x-stable` as well. Any reason the style changes aren't reflected in this branch? Does the VA just use its own css file instead of this one?

**Comment by jbalboni** [comment]
@dmethvin-gov I don't see any style changes when I build my branch locally.

**Comment by dmethvin-gov** [comment]
I wiped node_modules and reinstalled. This is what I'm getting. Are you seeing any vulns after install?
screen shot 2019-02-14 at 1 47 21 pm

**Comment by jbalboni** [comment]
@dmethvin-gov I'm going off of the vets-website security check that excludes low severity issues and also skips dependencies in `devDependencies`. In that check, the security issue goes away with this change.

**Comment by dmethvin-gov** [comment]
I'll just land this one and create a new PR for the other updates. The issue with leaving security holes in the devDependencies is it can compromise the CI/CD environment, [this ESLint breach](https://nodesource.com/blog/a-high-level-post-mortem-of-the-eslint-scope-security-incident/) being a recent example.

**Pull request merged**
