### PR TITLE
Continue cleaning up component usage examples

### PR DESCRIPTION
**Pull request by bernars-usa**
## Description

Continuing work from #154, #138. This PR will clean up and consolidate form component and widget descriptions and code samples.

🚧 WIP 🚧

### CODE REVIEW

**Comment by bernars-usa** [comment]
These still need usage guidelines or more description information:

- [ ] Hidden contextual information
- [ ] Radio button
- [ ] Checkbox group
- [ ] Contextual error message
- [ ] Password
- [ ] Conditional form fields
- [ ] Sequential duplicate form groups
- [ ] Review page (needs to be broken into a separate topic)
- [ ] Required checkbox before form submission (needs new image, plus description)

**Comment by annekainicUSDS** [comment]
I'm picking up the items in the list above, and checking off ones I've done!

**Comment by annekainicUSDS** [comment]
Comments on the above list:
- Hidden contextual information: this requires importing a component from the VA design system, so I'm not sure how we should include documentation on this. Eventually we may want to copy the needed components for this functionality into us-forms-system.
- Password: not sure how this got added to the list, but we don't include anything around password fields in us-forms-system. There's a widget for passwords in react-jsonschema-form, but not sure if it works if imported directly into our code. If we have a user that requires a password field, I think we should create our own widget for it. But until there's a real need I think we should probably just remove the reference to password fields in these docs.

**Comment by bernars-usa** [comment]
> Hidden contextual information: this requires importing a component from the VA design system, so I'm not sure how we should include documentation on this.

Should we just remove it from the docs for now? Do we want an issue to import the component from the VA system?

> Password: not sure how this got added to the list, but we don't include anything around password fields in us-forms-system.

This was just listed in https://github.com/usds/us-forms-system/wiki/Inventory-of-Existing-Features. If you want, go ahead and remove it here, otherwise I can do it in another PR.

**Comment by bernars-usa** [comment]
I LOVE how this ended up. It's such a useful topic now! Thank you so much, @annekainicUSDS and @dmethvin-gov, for doing the heavy lifting here.

I just went through and did a final pass on the content. Just tweaked a few words here ant there, and also retitled the topic. 🖥 [Here it is rendered](https://github.com/usds/us-forms-system/blob/component-cleanup/docs/building-a-form/available-form-features-and-usage-guidelines.md).

Could I get a final 👍 on this? Once it's merged in, I'll go through the widgets and definitions topic and do a cleanup there, and link up things in other topics to these more referential topics.

**Pull request merged**
