### PR TITLE
Merge production back into master for 1.1.0 release

### PR DESCRIPTION
**Pull request by annekainicUSDS**
## Description

After merging in [the latest release to production](https://github.com/usds/us-forms-system/pull/216), I went to merge production back into master to update master with the upgrade in package version.

However, I encountered [a problem with that PR](https://github.com/usds/us-forms-system/compare/production?expand=1) from production into master, where I noticed two things:

1. It was including 2 commits, both the most recent release and the one before it. It should have only been including the most recent release, because the release before it was already merged into master [here](https://github.com/usds/us-forms-system/pull/146). However, I think this previous commit was accidentally erased at some point because I can't find it in the commit history on master. I know we had encountered a few of Dave's commits that were mysteriously erased at one point, and I think this was another one of those that got erased.

2. The PR was also tracking a bunch of "changes" that were actually current on master. I don't really know why it was doing this, but I assume it is related to the first problem.

The issue of merging the latest on production into master is further complicated by the fact that additional commits have made it into master since the latest release was created, so production and master _should_ be different. We just want to update the change in package number on master.

In order to fix this problem, I created a new branch, resolve-merge-conflict-from-latest-production-release, which is branched off the latest from master. I then merged production into this new branch, and resolved the merge conflicts in two ways:
1. Where there was a merge conflict relating to the package version, I resolved it in favor of what's on production (i.e., upgrading from 1.0.1 to 1.1.0)
2. Where there was a merge conflict relating to anything else (i.e., additional commits that are on master and not yet released), I resolved those in favor of what's on master.

This means master should be updated with the changes on production, but the additional commits on master haven't been overwritten. I'm now creating a PR from resolve-merge-conflict-from-latest-production-release into master.

Hopefully this fixes the problem and subsequent releases don't encounter the same issue. I think we should have a retrospective as a team once @dmethvin-gov is back on how this occurred and how we can prevent it from occurring in the future.

### CODE REVIEW

**Comment by dmethvin-gov** [comment]
Sooo... I think the problem is that the changes in `production` are now squashed into a single commit that represents more than 100 individual commits to master. When we try to merge it back into `master` git looks at the diffs and sees a bunch of changes, some of which conflict (at least *en passant*) when individual `master` commits are applied. If `production` had the same commit hashes as `master` it wouldn't make that mistake and could see the progression.

BTW, I think [this is the full comparison](https://github.com/usds/us-forms-system/compare/production...2e9c1f17afe7bebc1418abc095254084c6cb0dcb) between the two branches, the last commit in master was the one for that security fix.

It seems like we should be using merge commits (rather than squashes) for our syncs between these two branches so that we can see which exact commit hashes are being used. In particular, when merging this back to `master` the position in the history should reflect when the release was actually done and not when this PR was rebased from `production` to `master`. 

However, I still think that for most other situations it makes sense to squash all the commits in a PR, otherwise history looks like a mess (as it does right now) and it's easy to miss problems before landing PRs or track them down after the fact. 

I'm not completely sure what the best resolution is for this.  Technically `production` is now public and we shouldn't change it, so I guess we can't fix the squashed commit there. Most likely we should just land this PR as a merge? This is not something I've dealt with, git is one of those tools with 1,000 different ways to use it and GitHub adds its own set of rules on top of that.

**Comment by annekainicUSDS** [comment]
@dmethvin-gov I did some digging around and asked the Vets.gov team, and I think you're right we should use squash commits for all feature merges into master, and merge commits for releases and syncs between production and master. I think this requires changing a setting in the repo to allow merge commits, which I think we disabled. Enabling it will enable us to decide if we want to squash commit or merge commit, which might mean we will accidentally commit the wrong way at the wrong time (lots of little commits on master for each PR is something we want to avoid), but I don't think we can create rules for different scenarios to restrict certain kinds of commits.

Vets.gov has automatic deployments now where releases are created using tags. They don't do a git branching workflow anymore. Do you think we should be using git tags as well? Even if we want to maintain our git branching workflow we can still add tags. Never used it before so not sure how useful it is!

**Comment by annekainicUSDS** [comment]
Also I think you're right, there may not be much we can do to retroactively fix production, but at least we can do the right thing going forward! And I think this PR will clean up some of the confusion, as it uses the same commit that's on prod now.

**Comment by dmethvin-gov** [comment]
Originally I was going to use a git tag approach and have CircleCI push the release from master, but I can't recall what the issue was there. I'll have to revisit that.

**Pull request merged**
